"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-03-10

Hand-written migration (NOT autogenerated).
autogenerate omits composite indexes per Pitfall 4 in RESEARCH.md.
All composite indexes are created within this migration so they exist
BEFORE any data load instruction runs.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # 1. games — no FK dependencies; created first                        #
    # ------------------------------------------------------------------ #
    op.create_table(
        "games",
        sa.Column("game_id", sa.String(20), primary_key=True, nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("home_team", sa.String(3), nullable=False),
        sa.Column("away_team", sa.String(3), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("stadium", sa.String(100), nullable=True),
        sa.Column("weather_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("idx_games_season_week", "games", ["season", "week"])
    op.create_index("idx_games_teams", "games", ["home_team", "away_team"])

    # ------------------------------------------------------------------ #
    # 2. play_by_play — FK to games                                       #
    # ------------------------------------------------------------------ #
    op.create_table(
        "play_by_play",
        sa.Column("id", sa.BigInteger(), autoincrement=True, primary_key=True, nullable=False),
        sa.Column("game_id", sa.String(20), sa.ForeignKey("games.game_id"), nullable=True),
        sa.Column("play_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("posteam", sa.String(3), nullable=True),
        sa.Column("defteam", sa.String(3), nullable=True),
        sa.Column("play_type", sa.String(20), nullable=True),
        sa.Column("yards_gained", sa.SmallInteger(), nullable=True),
        sa.Column("down", sa.SmallInteger(), nullable=True),
        sa.Column("ydstogo", sa.SmallInteger(), nullable=True),
        sa.Column("passer_player_id", sa.String(20), nullable=True),
        sa.Column("receiver_player_id", sa.String(20), nullable=True),
        sa.Column("rusher_player_id", sa.String(20), nullable=True),
        sa.Column("pass_touchdown", sa.SmallInteger(), nullable=True),
        sa.Column("rush_touchdown", sa.SmallInteger(), nullable=True),
        sa.Column("interception", sa.SmallInteger(), nullable=True),
        sa.Column("epa", sa.Numeric(8, 4), nullable=True),
        sa.Column("wp", sa.Numeric(6, 4), nullable=True),
        sa.UniqueConstraint("game_id", "play_id", name="uq_pbp_game_play"),
    )
    # 6 required composite indexes on play_by_play — must exist before data load
    op.create_index("idx_pbp_season_week", "play_by_play", ["season", "week"])
    op.create_index("idx_pbp_posteam_season", "play_by_play", ["posteam", "season"])
    op.create_index("idx_pbp_defteam_season", "play_by_play", ["defteam", "season"])
    op.create_index("idx_pbp_play_type_season", "play_by_play", ["play_type", "season", "week"])
    op.create_index("idx_pbp_passer_season", "play_by_play", ["passer_player_id", "season"])
    op.create_index("idx_pbp_receiver_season", "play_by_play", ["receiver_player_id", "season"])

    # ------------------------------------------------------------------ #
    # 3. player_stats — no FK to games                                    #
    # ------------------------------------------------------------------ #
    op.create_table(
        "player_stats",
        sa.Column("id", sa.BigInteger(), autoincrement=True, primary_key=True, nullable=False),
        sa.Column("player_id", sa.String(20), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("team", sa.String(3), nullable=True),
        sa.Column("position", sa.String(5), nullable=True),
        sa.Column("completions", sa.SmallInteger(), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=True),
        sa.Column("passing_yards", sa.SmallInteger(), nullable=True),
        sa.Column("passing_tds", sa.SmallInteger(), nullable=True),
        sa.Column("interceptions", sa.SmallInteger(), nullable=True),
        sa.Column("carries", sa.SmallInteger(), nullable=True),
        sa.Column("rushing_yards", sa.SmallInteger(), nullable=True),
        sa.Column("rushing_tds", sa.SmallInteger(), nullable=True),
        sa.Column("receptions", sa.SmallInteger(), nullable=True),
        sa.Column("targets", sa.SmallInteger(), nullable=True),
        sa.Column("receiving_yards", sa.SmallInteger(), nullable=True),
        sa.Column("receiving_tds", sa.SmallInteger(), nullable=True),
        sa.Column("fantasy_points_ppr", sa.Numeric(7, 2), nullable=True),
        sa.UniqueConstraint(
            "player_id", "season", "week", name="uq_playerstats_player_season_week"
        ),
    )
    op.create_index("idx_playerstats_player_season", "player_stats", ["player_id", "season"])
    op.create_index("idx_playerstats_season_week", "player_stats", ["season", "week"])

    # ------------------------------------------------------------------ #
    # 4. ngs_stats — AWS Next Gen Stats (no FK to games)                  #
    # ------------------------------------------------------------------ #
    op.create_table(
        "ngs_stats",
        sa.Column("id", sa.BigInteger(), autoincrement=True, primary_key=True, nullable=False),
        sa.Column("player_gsis_id", sa.String(20), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("stat_type", sa.String(10), nullable=False),
        sa.Column("team_abbr", sa.String(3), nullable=True),
        sa.Column("player_position", sa.String(5), nullable=True),
        # Passing fields
        sa.Column("avg_time_to_throw", sa.Numeric(5, 2), nullable=True),
        sa.Column("avg_completed_air_yards", sa.Numeric(5, 2), nullable=True),
        sa.Column("aggressiveness", sa.Numeric(5, 2), nullable=True),
        # Receiving fields
        sa.Column("avg_separation", sa.Numeric(5, 2), nullable=True),
        sa.Column("avg_cushion", sa.Numeric(5, 2), nullable=True),
        sa.Column("avg_yac_above_expectation", sa.Numeric(5, 2), nullable=True),
        # Rushing fields
        sa.Column("efficiency", sa.Numeric(5, 2), nullable=True),
        sa.Column("rush_yards_over_expected", sa.Numeric(5, 2), nullable=True),
        sa.Column("avg_time_to_los", sa.Numeric(5, 2), nullable=True),
        # Forward-compatible Phase 6 column (RESEARCH.md open question — nullable)
        sa.Column("press_man_rate", sa.Numeric(5, 2), nullable=True),
        sa.UniqueConstraint(
            "player_gsis_id", "season", "week", "stat_type",
            name="uq_ngs_player_season_week_type",
        ),
    )
    op.create_index("idx_ngs_player_season", "ngs_stats", ["player_gsis_id", "season"])
    op.create_index("idx_ngs_season_week_type", "ngs_stats", ["season", "week", "stat_type"])

    # ------------------------------------------------------------------ #
    # 5. odds_snapshots — FK to games                                     #
    # ------------------------------------------------------------------ #
    op.create_table(
        "odds_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, primary_key=True, nullable=False),
        sa.Column("game_id", sa.String(20), sa.ForeignKey("games.game_id"), nullable=True),
        sa.Column("sportsbook", sa.String(50), nullable=False),
        sa.Column("market_type", sa.String(30), nullable=False),
        sa.Column("line", sa.Numeric(6, 2), nullable=True),
        sa.Column("price", sa.SmallInteger(), nullable=True),
        sa.Column(
            "snapped_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("idx_odds_game_market", "odds_snapshots", ["game_id", "market_type"])
    op.create_index(
        "idx_odds_snapped_at_desc",
        "odds_snapshots",
        ["snapped_at"],
        postgresql_ops={"snapped_at": "DESC"},
    )


def downgrade() -> None:
    # Drop in reverse FK dependency order
    op.drop_table("odds_snapshots")
    op.drop_table("ngs_stats")
    op.drop_table("player_stats")
    op.drop_table("play_by_play")
    op.drop_table("games")
